'use server';
/**
 * @fileOverview An AI Prompt Optimization Tool that allows users to test and refine prompts.
 *
 * - aiPromptOptimization - A function that handles the AI prompt optimization process.
 * - AIPromptOptimizationInput - The input type for the aiPromptOptimization function.
 * - AIPromptOptimizationOutput - The return type for the aiPromptOptimization function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIPromptOptimizationInputSchema = z.object({
  originalPrompt: z.string().describe('The AI prompt that the user wants to test and optimize.'),
  userQuery: z.string().describe('The specific query or scenario the user will use to test the prompt.'),
  additionalContext: z.string().optional().describe('Any additional context or requirements for refining the prompt.'),
});
export type AIPromptOptimizationInput = z.infer<typeof AIPromptOptimizationInputSchema>;

const AIPromptOptimizationOutputSchema = z.object({
  optimizedPrompt: z.string().describe('The refined and optimized version of the prompt.'),
  evaluation: z.string().describe('An evaluation of the original prompt based on the user query, highlighting strengths and weaknesses.'),
  suggestions: z.string().describe('Suggestions for further improvements or alternative strategies for the prompt.'),
  testResponse: z.string().describe('A sample response generated by the AI using the optimized prompt and the user query, to demonstrate its effectiveness.'),
});
export type AIPromptOptimizationOutput = z.infer<typeof AIPromptOptimizationOutputSchema>;

export async function aiPromptOptimization(input: AIPromptOptimizationInput): Promise<AIPromptOptimizationOutput> {
  return aiPromptOptimizationFlow(input);
}

const aiPromptOptimizationPrompt = ai.definePrompt({
  name: 'aiPromptOptimizationPrompt',
  input: {schema: AIPromptOptimizationInputSchema},
  output: {schema: AIPromptOptimizationOutputSchema},
  prompt: `You are an AI prompt optimization assistant. Your goal is to help users refine their AI prompts for specific use cases.
Given an original prompt and a user query for testing, you need to:

1.  Provide an evaluation of how well the original prompt is likely to perform with the user query. Highlight its strengths and weaknesses.
2.  Suggest an optimized prompt that improves upon the original for the given user query and desired outcome.
3.  Provide further suggestions for improvements or alternative approaches that could enhance the prompt's performance.
4.  Finally, generate a test response as if you were an AI responding to the user query using the optimized prompt. This response should demonstrate the effectiveness of the optimized prompt.

Original Prompt:
{{{originalPrompt}}}

User Query for Testing:
{{{userQuery}}}

{{#if additionalContext}}
Additional Context for Refinement:
{{{additionalContext}}}
{{/if}}`,
});

const aiPromptOptimizationFlow = ai.defineFlow(
  {
    name: 'aiPromptOptimizationFlow',
    inputSchema: AIPromptOptimizationInputSchema,
    outputSchema: AIPromptOptimizationOutputSchema,
  },
  async (input) => {
    const {output} = await aiPromptOptimizationPrompt(input);
    if (!output) {
      throw new Error('AI prompt optimization failed to produce output.');
    }
    return output;
  }
);
